name: Build Docker Images for OpenCV Versions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opencv_version: 
          # OpenCV_4 versions
          #- 4.0.0
          #- 4.1.0
          #- 4.1.1
          - 4.1.2
          # OpenCV_3 versions
          #- 3.1.0
          #- 3.4.0
          #- 3.4.1
          #- 3.4.2      
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: false                # Disable submodules if they are not required
        persist-credentials: false        # Avoid persisting credentials
        fetch-depth: 1                    # Only fetch the latest commit

    - name: Remove Git Extraheader
      run: |
        git config --global --unset-all http.https://github.com/.extraheader || true


    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/arm/v7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}  # Using secret for GitHub username
        password: ${{ secrets.GH_TOKEN }}      # Using secret for access token


    - name: Build Docker Image for OpenCV 4.1.0
      run: |
        cd opencv_4/4.1.2
        docker buildx build --platform linux/arm/v7 -t ghcr.io/${{ github.repository_owner }}/my_pi_opencv_img:4.1.2 --load .

    - name: Test OpenCV Installation
      run: |
        docker run --rm --platform linux/arm/v7 ${{ github.repository_owner }}/ my_pi_opencv_img:4.1.2 python -c "import cv2; print('Installed OpenCV version is: {} :)'.format(cv2.__version__))"

     
    - name: Push Docker Image to GitHub Packages
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/my_pi_opencv_img:4.1.2   