name: Build Docker Images for OpenCV Versions

on:
  push:
    branches:
      - master
    tags:
      - 'v1'   
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opencv_version: 
          # OpenCV_4 versions
          #- 4.0.0
          #- 4.1.0
          - 4.1.1
          #- 4.1.2
          # OpenCV_3 versions
          #- 3.1.0
          #- 3.4.0
          #- 3.4.1
          #- 3.4.2      
    env:
      REPO_OWNER: "${{ github.repository_owner }}"  # Define the repository owner in lowercase manually if needed

    steps:
    - name: Set lowercase repo owner
      run: |
        echo "REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: false
        persist-credentials: false
        fetch-depth: 1

    - name: Remove Git Extraheader
      run: |
        git config --global --unset-all http.https://github.com/.extraheader || true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/arm/v7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build Docker Image for OpenCV 4.1.2
      run: |
        cd opencv_4/4.1.2
        docker buildx build --platform linux/arm/v7 -t ghcr.io/${{ env.REPO_OWNER }}/my_pi_opencv_img:4.1.2 --load .

    #- name: Run OpenCV 
    #  run: |
    #   docker run --rm --platform linux/arm/v7 --init=false ghcr.io/${{ env.REPO_OWNER }}/my_pi_opencv_img:4.1.2 python -c "import cv2; print('Installed OpenCV version is: {} :)'.format(cv2.__version__))"


    - name: Push Docker Image to GitHub Packages
      run: |
        docker push ghcr.io/${{ env.REPO_OWNER }}/my_pi_opencv_img:4.1.2
